### PR TITLE
fix missing $ in makeeec.script

### PR DESCRIPTION
**Pull request by dmcoles**

### CODE REVIEW

**Comment by dmcoles** [comment]
with these changes it should now be fully working.

ppcifuncs should now be assembling correctly as well (tested under OS4)

**Comment by SamuraiCrow** [comment]
`support.e` still doesn't work with EVO 3.5.0 but should be easily fixed based on the commits since then.

**Comment by dmcoles** [comment]
Yep it won't compile with 3.5.0 - I have already made the necessary fixes. I can send you a updated version of Evo. I'm planning to release it in the near future

**Comment by SamuraiCrow** [comment]
Go ahead with your release process.  I can wait.

**Comment by dmcoles** [comment]
Does the morphos version work correctly?

**Comment by SamuraiCrow** [comment]
I haven't gotten it to compile yet but I have a clone of the latest EVO source on my hard drive.

**Comment by dmcoles** [comment]
It should compile using testec

**Comment by SamuraiCrow** [comment]
TestEC doesn't load modules from a local directory unless it's marked with an astsrisk at the beginning.  Otherwise it's assumed to be in the EModules: directory.

**Comment by dmcoles** [comment]
Same with evo. So what is it that's failing? I'm able to build eec.020 using testec and then build eec.os4 using eec.020

**Comment by dmcoles** [comment]
full set of EEC executables and the ecxmodules:eec folder

I installed morphos today using QEMU and eec.mos seemed to work when compiling a couple of the example sources included with ecx

[eec.zip](https://github.com/EEC-Developers/eec/files/9496365/eec.zip)

**Comment by SamuraiCrow** [comment]
Thanks.  If you could update the build instructions regarding EVO it would be much appreciated.

**Comment by dmcoles** [comment]
yes sure, once i have released the updated evo I can update the build instructions.

**Pull request merged**
